[project]
name = "MOODS-python"
version = "1.9.4.1"
authors = [
	{name = "Janne H. Korhonen", email = "janne.h.korhonen@gmail.com"}
]
description = 'MOODS: Motif Occurrence Detection Suite'
classifiers = ["Topic :: Scientific/Engineering :: Bio-Informatics"]
keywords = ["PWM", "PSSM", "motif scan"]
readme = "readme.MD"
license = "GPL-3.0-or-later OR LicenseRef-Biopython"
license-files = ["COPYING.GPLv3", "COPYING.BIOPYTHON"]
# We currently have the following constraints:
# – F-strings (used in some of the scripts) require Python 3.6.
# – setuptools 61, which has tool.setuptools-script-files, requires Python 3.7. 
# – setuptools 77 is needed or parsing the licence information (above) correctly and requires Python 3.9.
requires-python= ">=3.9" 

[project.urls]
Homepage = 'https://www.cs.helsinki.fi/group/pssmfind/'

[build-system]
requires = ["setuptools >=77", "swig"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
script-files = ['scripts/moods-dna.py']
