[project]
name = "MOODS-python"
version = "1.9.4.1"
authors = [
	{name = "Janne H. Korhonen", email = "janne.h.korhonen@gmail.com"}
]
description = 'MOODS: Motif Occurrence Detection Suite'
classifiers = ["Topic :: Scientific/Engineering :: Bio-Informatics"]
keywords = ["PWM", "PSSM", "motif scan"]
readme = "readme.MD"
license = "GPL-3.0-or-later OR LicenseRef-Biopython"
license-files = ["COPYING.GPLv3", "COPYING.BIOPYTHON"]
requires-python= ">=3.6" # setuptools 61 and f-strings require Python 3.6.

[project.urls]
Homepage = 'https://www.cs.helsinki.fi/group/pssmfind/'

[build-system]
requires = ["setuptools >=61", "swig"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
script-files = ['scripts/moods-dna.py']
